CREATE DATABASE burgers_db;
USE burgers_db;
CREATE TABLE burgers (
	id INTEGER (11) AUTO_INCREMENT,
	burgername VARCHAR (40),
	devoured BOOLEAN DEFAULT FALSE,
	date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id)

);
